
export const ramais = [
    { local: "Recepção 1", unidade: "COB", ramal: "5031" },
    { local: "Recepção 2", unidade: "COB", ramal: "5024" },
    { local: "Recepção Exames", unidade: "COB", ramal: "5018" },
    { local: "Michele Oliveira", unidade: "COB", ramal: "5012" },
    { local: "Consultório 1", unidade: "COB", ramal: "5013" },
    { local: "Consultório 2", unidade: "COB", ramal: "5025" },
    { local: "Consultório 3", unidade: "COB", ramal: "5017" },
    { local: "Dr José Carlos", unidade: "COB", ramal: "5022" },
    { local: "Juliana Ribeiro", unidade: "COB", ramal: "5014" },
    { local: "Hérika Quaresma", unidade: "COB", ramal: "5015" },
    { local: "Recepção 1", unidade: "Botafogo", ramal: "5041" },
    { local: "Recepção 2", unidade: "Botafogo", ramal: "5065" },
    { local: "Recepção exames", unidade: "Botafogo", ramal: "5011" },
    { local: "Faturamento", unidade: "Botafogo", ramal: "5056" },
    { local: "Recepção Centro Cirurgico", unidade: "Botafogo", ramal: "5002" },
    { local: "Marketing", unidade: "Botafogo", ramal: "5020" },
    { local: "Centro cirúrgico", unidade: "Botafogo", ramal: "5021" },
    { local: "RH", unidade: "Botafogo", ramal: "5051" },
    { local: "Joana", unidade: "Botafogo", ramal: "5049" },
    { local: "Financeiro", unidade: "Botafogo", ramal: "5058" },
    { local: "TI", unidade: "Botafogo", ramal: "5066" },
    { local: "Rafael Macedo", unidade: "Botafogo", ramal: "5010" },
    { local: "Compras", unidade: "Botafogo", ramal: "5052" },
    { local: "Supervisão", unidade: "Nilópolis", ramal: "5101" },
    { local: "Recepção 1", unidade: "Nilópolis", ramal: "5102" },
    { local: "Recepção 2", unidade: "Nilópolis", ramal: "5103" },
    { local: "Recepção exames 1", unidade: "Nilópolis", ramal: "5104" },
    { local: "Recepção exames 2", unidade: "Nilópolis", ramal: "5105" },
    { local: "Centro cirúrgico", unidade: "Nilópolis", ramal: "5106" },
    { local: "Supervisora", unidade: "Nilópolis", ramal: "5107" },
    { local: "Supervisora", unidade: "SJM", ramal: "5201" },
    { local: "Recepção 1", unidade: "SJM", ramal: "5202" },
    { local: "Recepção 2", unidade: "SJM", ramal: "5203" },
    { local: "Centro cirúrgico", unidade: "SJM", ramal: "5204" },
    { local: "Supervisora", unidade: "Magé", ramal: "5401" },
    { local: "Recepção SUS 1", unidade: "Magé", ramal: "5402" },
    { local: "Recepção SUS 2", unidade: "Magé", ramal: "5403" },
    { local: "Recepção Part 1", unidade: "Magé", ramal: "5404" },
    { local: "Recepção CC", unidade: "Magé", ramal: "5405" },
    { local: "Centro Cirúrgico", unidade: "Magé", ramal: "5406" },
    { local: "Faturamento", unidade: "Magé", ramal: "5407" },
    { local: "Supervisora", unidade: "Lagos", ramal: "5301" },
    { local: "Recepção SUS 1", unidade: "Lagos", ramal: "5302" },
    { local: "Recepção SUS 2", unidade: "Lagos", ramal: "5303" },
    { local: "Recepção SUS 3", unidade: "Lagos", ramal: "5304" },
    { local: "Recepção Part 1", unidade: "Lagos", ramal: "5305" },
    { local: "Recepção Part 2", unidade: "Lagos", ramal: "5306" },
    { local: "Recepção CC", unidade: "Lagos", ramal: "5307" },
    { local: "Centro Cirúrgico", unidade: "Lagos", ramal: "5308" },
    { local: "Faturamento", unidade: "Lagos", ramal: "5309" },
    { local: "Supervisor", unidade: "Call Center", ramal: "6000" },
    { local: "PA 1", unidade: "Call Center", ramal: "6001" },
    { local: "PA 2", unidade: "Call Center", ramal: "6002" },
    { local: "PA 3", unidade: "Call Center", ramal: "6003" },
    { local: "PA 4", unidade: "Call Center", ramal: "6004" },
    { local: "PA 5", unidade: "Call Center", ramal: "6005" },
    { local: "PA 6", unidade: "Call Center", ramal: "6006" },
    { local: "PA 7", unidade: "Call Center", ramal: "6007" },
    { local: "PA 8", unidade: "Call Center", ramal: "6008" },
    { local: "PA 9", unidade: "Call Center", ramal: "6009" },
    { local: "PA 10", unidade: "Call Center", ramal: "6010" }
];

export const cards = [
    { href: "https://webmail-seguro.com.br/hobotafogo.com.br/", icon: "fa-envelope", title: "Webmail", text: "Acesse seu e-mail institucional." },
    { href: "#", icon: "fa-folder-open", title: "Central de Documentos", text: "POPs, Manuais e Arquivos dos Setores." },
    { href: "#", icon: "fa-phone", title: "Ramais Internos", text: "Contatos e telefones úteis por unidade.", onClick: "abrirRamais" },
    { href: "#", icon: "fa-users", title: "Rede Corporativa", text: "Informativos, feedbacks e canal com o RH." },
    { href: "#", icon: "fa-chalkboard-teacher", title: "Trilhas de Treinamento", text: "Cursos, certificados e evolução profissional." },
    { href: "#", icon: "fa-headset", title: "Abertura de Chamados", text: "Solicitações para TI, RH e Administrativo." },
    { href: "#", icon: "fa-poll", title: "Pesquisas e Avaliações", text: "Clima organizacional e feedbacks 360°." },
    { href: "#", icon: "fa-lightbulb", title: "Caixa de Sugestões", text: "Ideias para melhorar nosso ambiente." },
    { href: "#", icon: "fa-award", title: "Reconhecimentos", text: "Colaboradores destaque e boas práticas." }
];
